version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SECRET_KEY=&+y@(2660ma21l8e=b8znrhrvl3e30tcn3k8uo!uv)t(ug*u+@
      - DEBUG=1
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
